### ISSUE TITLE
ReferenceError: alert is not defined

### ISSUE THREAD

**Issue by oosap** [NguyenDanPhuong/MangaRipper#102]
Receiving this message when trying to download "Made in Abyss" from kissmanga. Any help would be great.

url: http://kissmanga.com/Manga/Made-in-Abyss

**Comment by eksynn** [comment]
same, but with onepunch-man - oddly enough, it managed to download the first two chapters from kissmanga lol

here's the error: http://prntscr.com/h91gi3

edit: trying to click "start download" after the error comes up seems to start the download. testing it a second time gave me another error (sorry, forgot to capture it... so i tried again after closing and reopening, got the same ReferenceError, but pressing start download again worked again.)

**Comment by NguyenDanPhuong** [comment]
Tested and work fine.
