### ISSUE TITLE
TypeError: 'CryptoJS.SHA256' is not a function

### ISSUE THREAD

**Issue by Remixful** [NguyenDanPhuong/MangaRipper#103]
Getting the error "TypeError: 'CryptoJS.SHA256' is not a function" when downloading from KissManga. 
Manga link: http://kissmanga.com/Manga/Liar-Game/

Restarting the download fixes it but it still appears from time to time. A retry download option would be nice maybe.

**Comment by NguyenDanPhuong** [comment]
Tested and work fine.
