### ISSUE TITLE
Invalid URI, must be absolute URI or Base Address must be set?

### ISSUE THREAD

**Issue by grumbleGB** [NguyenDanPhuong/MangaRipper#106]
[2017-11-13.log](https://github.com/NguyenDanPhuong/MangaRipper/files/1468650/2017-11-13.log)
![error](https://user-images.githubusercontent.com/33639686/32749742-29a26802-c8b8-11e7-8b22-c77c636253d5.PNG)

**Comment by GambitKZ** [comment]
Ah, I do remember something like that. They had the address like "~/manganame/bla-bla". But I thought that we have fixed that. I will try to take a look on weekends.
