### ISSUE TITLE
Manga fox changed their URL

### ISSUE THREAD

**Issue by DanteLucis** [NguyenDanPhuong/MangaRipper#109]
Old: mangafox.me
New: mangafox.la
[2017-02-13.log](https://github.com/NguyenDanPhuong/MangaRipper/files/1537571/2017-02-13.log)

**Comment by moax101** [comment]
Any News how to download in mangafox again?

**Comment by NguyenDanPhuong** [comment]
I've fixed it. Please check the latest version :)

**Comment by moax101** [comment]
Where?
