### ISSUE TITLE
Allow integrated compression of downloaded chapters

### ISSUE THREAD

**Issue by diras2010** [NguyenDanPhuong/MangaRipper#11]
MangaCrawler's style of download the chapters, sort them numerically or by index , and then compress them in cbz format woudl be awesome, if my memory doesn't fail me, the source code (of MangaCrawler) is on GitHub as well

**Comment by NguyenDanPhuong** [comment]
Nice idea. I will take a look at this.

**Comment by diras2010** [comment]
i checked about the Manga Crawler repository, its stored in Codeplex

http://mangacrawler.codeplex.com/SourceControl/latest

**Comment by NguyenDanPhuong** [comment]
I added the feature to download manga as CBZ. Please download latest version from https://github.com/NguyenDanPhuong/MangaRipper/releases/tag/1.0.115
