### ISSUE TITLE
Mangaripper.core

### ISSUE THREAD

**Issue by canwenot** [NguyenDanPhuong/MangaRipper#111]
I am having an issue and cannot find an answer already available and cannot figure this out myself, I am not very techy but i love manga, so please help me!

![this is annoying](https://user-images.githubusercontent.com/34407830/33801151-640cfaea-dd06-11e7-9d42-c3327ad81feb.png)

when ever i try any url this is what i get,  I unpack the folder from the original zip to a folder just inside my user folder, Im running windows 7, and this is basically my last option, I have found no where else to download manga.
if you can help me if im doing something wrong please let me know,  or if it just wont work for me please help me find some why of getting manga! T-T I need it in my life so Please!

**Comment by GambitKZ** [comment]
Heh, looks like the title and Description are switched.
The issue here is "m." in the URL, never heard that they have the site for the mobile version.
Oh, and you paste the chapter page instead of root URL. Try again with the "http://mangafox.la/manga/maou_no_hajimekata/" URL.

**Comment by canwenot** [comment]
.................................................................................well that m. seems to have the issue, or not? 

Sooooooooooo: this link takes me to a no content page: http://mangafox.la/manga/maou_no_hajimekata/v01/c001/
but this one is a fully functional link with all pages: http://m.mangafox.la/manga/maou_no_hajimekata/v01/c001/1.html
Can we get a patch? fast? if this works all the old hidden content on Mangafox could be re-accessed at least for a while?

**Comment by GambitKZ** [comment]
>well that m. seems to have the issue, or not?
Yes, it is. 
>http://mangafox.la/manga/maou_no_hajimekata/v01/c001/
Anyway, it's just ONE chapter. MangaRipper working with the WHOLE series.

>Can we get a patch? 
Why should we do it, if it's working perfectly fine? Have you even tried the link which I have provided above? Here is the result:
![image](https://user-images.githubusercontent.com/17333840/33803492-1392a572-ddbc-11e7-99de-2f4226bc7db8.png)

**Comment by canwenot** [comment]
.................................................................................well that m. seems to have the issue, or not? 

Sooooooooooo: this link takes me to a no content page: http://mangafox.la/manga/maou_no_hajimekata/v01/c001/
but this one is a fully functional link with all pages: http://m.mangafox.la/manga/maou_no_hajimekata/v01/c001/1.html
Can we get a patch? fast? if this works all the old hidden content on Mangafox could be re-accessed at least for a while?

**Comment by canwenot** [comment]
you didn't try to download the chapters did you? it doesn't work. and if you go to the site with out the .m they dont show up, it shows a dead end message, I figured that it was a site that was hiding its data in a sub of the primary so any one going in for legal complaints would find it gone and leave them be, all the while the content fully accessible via the alternate section of m.
So, can we please get a patch?

**Comment by GambitKZ** [comment]
> you didn't try to download the chapters did you?

I have done it two times just to test it.  And they downloaded perfectly.  Even my previous screen shows the progress of downloading.

>and if you go to the site without the .m they don't show up, it shows a dead end message,

In my case, it shows the notification where all you need to do is to press "Please click here to continue reading."
![image](https://user-images.githubusercontent.com/17333840/33808906-1dfb16a0-de18-11e7-8cef-7fecdabfc629.png)
Maybe the WebSite is blocked in your country, but the mobile version is not?

>I figured that it was a site that was hiding its data in a sub of the primary so anyone going in for legal complaints would find it gone and leave them be, all the while the content fully accessible via the alternate section of m.

Nope, it's the way to separate Mobile and Desktop versions of the sites.

Personally, I can't see any problems, so no patch from my side. It's either you do something wrong, or the original site is blocked. I think the first one is more possible.

**Comment by canwenot** [comment]
Ok then I dont know whats wrong!  
"Parse Content failed! Please check if you can access this content on your browser"
that's the error message i get when i try to download it with out the m. but with it i get the mangaripper.core message, so now what do i do?
I have a guess, that the file isn't supposed to be available in my country, is there a way to use a proxy server in conjunction with this program?

**Comment by NguyenDanPhuong** [comment]
MangaRipper doesn't support proxy but you can use VPN
