### ISSUE TITLE
bato.to error

### ISSUE THREAD

**Issue by BaganLee** [NguyenDanPhuong/MangaRipper#113]
I am getting an error when I am trying to download a manga for bato and I have downloaded the last version of the mangaripper 
logs ... https://pastebin.com/QeSXvDUv  .... https://pastebin.com/fvrXxQuY ... https://pastebin.com/ZNAWjhUb ... https://pastebin.com/dbvUYP7V  

https://imgur.com/a/wiyWS

**Comment by GambitKZ** [comment]
Have you set your login/password for Batoto into config?

**Comment by BaganLee** [comment]
Well... no I don't I didn't know that you have to do something like that, how can I set them up ?

**Comment by GambitKZ** [comment]
Looks like we need to set specific error for this kind of issue.
You need to change them in the "MangaRipper.Configuration.json" file in the root folder
![image](https://user-images.githubusercontent.com/17333840/34024763-38283452-e176-11e7-9110-74d69ff6e5b0.png)

**Comment by BaganLee** [comment]
Thanks for the help.
