### ISSUE TITLE
URL for MangaHere is changed.

### ISSUE THREAD

**Issue by seiaxen** [NguyenDanPhuong/MangaRipper#115]
Hi,
As the title said, now MangaHere URL is changed from www.mangahere.co to www.mangahere.cc .

Would be glad if you guys update the core for mangahere.

Thanks.

-----
Calling Boss @GambitKZ  and Big Boss @NguyenDanPhuong

**Comment by NguyenDanPhuong** [comment]
It's fixed. Thank you for reporting.
