### ISSUE TITLE
Can't download from any source

### ISSUE THREAD

**Issue by tirafesi** [NguyenDanPhuong/MangaRipper#116]
I can't download from any website.

Here are 2 examples with screenshots:

``http://www.mangahere.cc/manga/nanatsu_no_taizai/``

![](https://i.imgur.com/r88WPSo.png)

``http://mangafox.la/manga/nanatsu_no_taizai/``

![](https://i.imgur.com/Bjwbhqw.png)

As you can see, *mangahere* doesn't even fetch the chapter list. Meanwhile, *mangafox*, despite being able to fetch the chapter list, doesn't let me download them.

**Comment by NguyenDanPhuong** [comment]
It's fixed. Thank you for reporting.
