### ISSUE TITLE
Enhancement  Request

### ISSUE THREAD

**Issue by iYatsumi** [NguyenDanPhuong/MangaRipper#12]
i was wondering if it was possible or maybe in the future to include more or simply have the option to add another supported site to the app like Kissmanga.com

**Comment by NguyenDanPhuong** [comment]
We can support for more sites but kissmanga.com don't want other app leech theirs images. I don't like to go again theirs will. Feel free to request support for another sites if you want. :)

**Comment by JedBurke** [comment]
Is it because of the JavaScript check?

**Comment by NguyenDanPhuong** [comment]
Yes. They spend too much effort blocking downloader.
