### ISSUE TITLE
Bato.to Closing Down Permanently

### ISSUE THREAD

**Issue by eksynn** [NguyenDanPhuong/MangaRipper#124]
just thought this should be brought up before it happens - if it hasn't already. just in case you're wondering why it suddenly stops working.
source: https://bato.to/forums/topic/28840-batoto-will-be-closing-permanently/

edit: probably old news though, as i just realised there's a new version that removes bato.to from its list xD

**Comment by GambitKZ** [comment]
b.t.w. The link redirected me to the "bato.to" website which is up and running.
Are we 100% sure that it will be closed?

**Comment by eksynn** [comment]
here's an archived post: https://web.archive.org/web/20180122102239/https://bato.to/forums/topic/28840-batoto-will-be-closing-permanently/

the first post, in specific:

> Hello everyone.
>
>  
> Batoto will be closing down permanently.
>  
> I just don't have the will to run this site anymore. This is not a sudden decision for me or something I make lightly, it has been on my mind for a couple years now. And I've finally made my mind to put it into action.
>  
> I started Batoto along with the crew from The Company back in January of 2011 and it's been a very meaningful part of my life. I don't regret taking on this hobby called Batoto and I cherish the role that I've played as well as the countless hours everyone else here has put in as well as the great community that we've built. I've come to see this like my baby. At 7 years, I suppose it's not even a baby anymore. But it is at a point where I need to move on with my life. I'm tired and I just can't do this anymore.
>  
> Batoto is proving to be ever more time consuming to maintain despite the fact that we have fewer real visitors. Our bot visitors are always growing as we're the only source that still gives true quality. I've made some serious and controversial changes to counter that like adding membership requirements. While that helped a ton at that time, it always creeps back and we're almost back to square one at this point when I look at the statistics. They currently make up roughly 35% of the traffic which are much more troublesome than real users. And I don't want to make more serious change to this site that'll inconvenience the readers even further. We've already lost enough.
>  
> It's not just the bots that adds to the technical issues. It's a big site with huge number of page views. It's just expected part of running the site. Whether it be a DDoS attack, scraper bots gone haywire, servers/hosting company being annoying, ad company being annoying, there's just so many stuff that I constantly have to deal with. Over the last 7 years, I haven't had a single day when I could just freely take a day off. If the site goes down, I had to be there, on my computer, ready to take action. I obviously don't do something every single day, but just making myself available is taxing on my life. The fact that I'm unable to take a vacation have often been a point of argument with others in my life. Anytime someone says, let's go somewhere, I could only say no. I have to be here. Sound sleeping is also a thing of the past. I have alarms that go off when the site goes down. I'd wake up in the middle of the sleep to take care of it. False alarm, while irritating, is one of the best things to see when I'm interrupted from my sleep. How else would I have always responded to issues immediately?
>  
> I've simply run out of will and I feel this is the best choice for me. I beg that the community understands this difficult decision I've made.
>  
>  
> Services will be severely affected starting January 18th as servers expire, though content may still be accessible for you. By January 25th, critical number of servers will have expired that the site will no longer function. But you should consider 18th to be the last day.
>  
>  
> I have stopped accepting donations for a several months now and I'll check to see if anyone sent anything directly and I'll be sure to refund them if they did.
>  
> Going forward, some of the staff members have and still are in the process of backing up the entire Batoto comic content as they have been notified of this decision well in advanced. They may choose to create a new Batoto or something simpler. That will be up to them, but I will no longer be part of running it.
>  
> I understand that our forum is a valuable form of communication for many. Because of that, I will be keeping the forums running for an extended period of time, date of which is not yet decided. I will also be making an export for your follows list so that your list isn't lost. Additionally, this list will be available as long as the forum is up and running. Other information that may be useful to the community may be filtered and backed up then made available for the community, but I will, under no circumstances, give anyone a full backup of the site or database. Many have used our system in confidence and it will stay that way.
>  
> I would like to thank everyone here for your patronage all these years. It has been a good run. Really, thank you. Wouldn't have made it this far without you.
>  
> ---------------------
>  
> Looks like a lot of people are in a scramble to save what they can, and as a result, site is lot slower. I'm turning on the cloudflare anti-ddos protection to put the site back to a manageable speed. Will likely need to keep it on until the end.
> - 2018/1/7
>  
> ---------------------
>  
> The export feature has been added. Go to my follows and check the side bar. Realized there isn't much data to save when our IDs and such are all gone. But it's there anyway for the fuller version.
> If domain is no longer up, forums will be available at the alternate address of vatoto.com (not used right now)
> - 2018/1/13
>  
> ---------------------
>  
> The servers have begun to expire. First the of the servers are now offline. With the exception of the main (control) server, it's designed so that load is shared among the rest when one goes down. So, it'll continually get slower to serve pages unless people trying to access also decreases. I will manually remove reader pages by 25th and migrate the forums away.
> - 2018/1/18
