### ISSUE TITLE
Mangafox new host name

### ISSUE THREAD

**Issue by anhxtaiii** [NguyenDanPhuong/MangaRipper#131]
thought you should know that mangafox changed their domain once again thus making mangafox.la not available to download any manga from their new site.

They are now using Fanfox.net

**Comment by NguyenDanPhuong** [comment]
When I go to Fanfox.net, it redirects me to http://mangazoneapp.com/ Is there any one can access the site help us to change the url and test it?

**Comment by TristisOris** [comment]
http://mangafox.be it's the same, as i can see.
can't download anyhing too.

**Comment by iYatsumi** [comment]
Works fine to me when i tried to access Fanfox.net as you can see

![image](https://user-images.githubusercontent.com/8799430/37135677-62dd9264-226c-11e8-9ee8-6a54ff0a0a08.png)

**Comment by NguyenDanPhuong** [comment]
I've fixed this in latest release. Thanks for report.
