### ISSUE TITLE
SSL/TLS Unhandled Exception [Ignorable?]

### ISSUE THREAD

**Issue by eksynn** [NguyenDanPhuong/MangaRipper#132]
I'm getting an error when i launch mangaripper...

https://pastebin.com/raw/f6xxMCzL

i can then either click continue (which just continues on) or quit, which immediately closes the app

please advise?

**Comment by iYatsumi** [comment]
im getting the same error 

![image](https://user-images.githubusercontent.com/8799430/37135733-a9379e08-226c-11e8-9fee-88745a829eb7.png)

Here's the log:
[2018-03-08.log](https://github.com/NguyenDanPhuong/MangaRipper/files/1791995/2018-03-08.log)

**Comment by BaganLee** [comment]
I am getting the same error too
[https://imgur.com/a/XtwtY](url)
Logs : https://pastebin.com/raw/655DWQ5w

**Comment by TromboneFreak** [comment]
Same issue, here. 1.0.321

[2018-03-29.log](https://github.com/NguyenDanPhuong/MangaRipper/files/1862538/2018-03-29.log)

**Comment by xthephreakx** [comment]
is there a know work around for this ?

**Comment by GambitKZ** [comment]
Sorry guys. Never got this kind of error.
The only useful information is in the @TromboneFreak  logs:
```
System.IO.FileNotFoundException: Could not find file ``
'C:\Users\ghost\AppData\Roaming\MangaRipper\Data\CommonSettings.json'.

`System.IO.FileNotFoundException: Could not find file 'C:\Users\ghost\AppData\Roaming\MangaRipper\Data\Bookmarks.json'.`
```

But I don't think it's the main reason here.

**Comment by xthephreakx** [comment]
I thought it might have something to do with windows updates. But did a clean install of windows 10 in a VM with no updates same error. Tried and older and a newer version. 

Does de application use any cerificates ? Could be due to an expired certificate because the complain is about ssl/stl

**Comment by GambitKZ** [comment]
> Does de application use any certificates

No, nothing of the sort.

> Will upload my log also but contains the same error and others

Do you mean you also have "System.IO.FileNotFoundException" or it's just a log without an error?

**Comment by xthephreakx** [comment]
yes thats what i mean:
| ERROR | ApplicationConfiguration | System.IO.FileNotFoundException: Could not find file 'C:\Users\Administrator\AppData\Roaming\MangaRipper\Data\CommonSettings.json'.

| ERROR | ApplicationConfiguration | System.IO.FileNotFoundException: Could not find file 'C:\Users\Administrator\AppData\Roaming\MangaRipper\Data\DownloadChapterTasks.json'.

both files exist in the Data folder and have the correct permissions

[2018-04-09.log](https://github.com/NguyenDanPhuong/MangaRipper/files/1891127/2018-04-09.log)

**Comment by GambitKZ** [comment]
And "Run as Admin" also didn't help?

**Comment by xthephreakx** [comment]
tried that first also disableing antivirus and firewall

**Comment by GambitKZ** [comment]
btw. what is shown if you press the "Details" button?

**Comment by xthephreakx** [comment]
[details.txt](https://github.com/NguyenDanPhuong/MangaRipper/files/1891354/details.txt)

**Comment by GambitKZ** [comment]
![image](https://user-images.githubusercontent.com/17333840/38517307-5be26d32-3c5b-11e8-9ad8-1dda279f4e47.png)

Maybe this part at blame here?

**Comment by xthephreakx** [comment]
could be i will edit it to see what it does

**Comment by xthephreakx** [comment]
could it be a .net issue ?

**Comment by GambitKZ** [comment]
@xthephreakx 
> could it be a .net issue?

I have no idea. It never worked, or it's just stopped suddenly?

Maybe you should install free VisualStudio Community - https://www.visualstudio.com/downloads/
Download the SourceCode:
![image](https://user-images.githubusercontent.com/17333840/38566183-e4acf8ae-3d04-11e8-8696-3f445801855c.png)

Open it in VisualStudio and press "Start"
![image](https://user-images.githubusercontent.com/17333840/38566261-1b3483e2-3d05-11e8-87b4-3232e6d5ec75.png)

This either fix it or at least you will catch an exception in the code.

Can't argue though that it's an overkill. However, it's hard to do anything if you can't reproduce it :(

**Comment by xthephreakx** [comment]
Main pc windows 10 worked until yesterday but haven’t used it since January. 

Thought it was windows updates so did a clean install of windows 10 same issue. Then tried a windows 7 machine which didn’t work either. So I was able to reproduce on 2 other machines. 

Will try your method but that will be tomorrow as I don’t have time tonight

**Comment by GambitKZ** [comment]
> CloudFlareUtilities.CloudFlareClearanceException: Clearance failed after 4 attempt(s).

Well, this is a known issue - #134 

> could you give me a bit more detail on how to do this.

In theory, everything should be simple. Just in case - step by step instruction:
1. Open Solution
2. Right click on Solution -> Restore NuGet Package
3. Right click on Solution -> Build Solution
![image](https://user-images.githubusercontent.com/17333840/38627859-c7931c1c-3dd1-11e8-8aec-a572d41798b1.png)
4.  Right click on "MangaRipper" project -> "Set as StartUp Project"
![image](https://user-images.githubusercontent.com/17333840/38627959-fd969834-3dd1-11e8-8219-07983946df7f.png)
5. Press "Start"
![image](https://user-images.githubusercontent.com/17333840/38627999-1873e5f8-3dd2-11e8-9af2-9f26e386ddba.png)

**Comment by xthephreakx** [comment]
been trying to get it to work but no succes unfortunatly ...

have you been able to replicate te issue ?

**Comment by GambitKZ** [comment]
@xthephreakx 
Unfortunately no.
But hey, if you have an issue with the access to "C:\Users\Administrator\AppData\" folder, how about putting the data into the root folder.
Could you please test this option:
[Debug.zip](https://github.com/NguyenDanPhuong/MangaRipper/files/1939151/Debug.zip)

**Comment by xthephreakx** [comment]
oke tried that no error message lik epreviously

now i get a "clearance failed agter 4 attempts" popup message
Download Canccelled! Reason: clearance failed agter 4 attempts

![image](https://user-images.githubusercontent.com/5319954/39170169-d836cbc2-479a-11e8-9d22-fd8602644670.png)

**Comment by GambitKZ** [comment]
@xthephreakx 
Woah, Woah. Hold your horses.

First of all, looks like the issue was with access to the "'C:\Users\Administrator\AppData\Roaming\MangaRipper\Data\" folder. I believe if you create a new windows user and run the original MangaRipper under this user - you will not get an error.

Second:
I have already mentioned the "clearance failed after 4 attempts" error two posts ago.
It's an error in 3-rd party library, so no MangaKiss for a while. 
And yes, we are watching over it - #134

**Comment by GambitKZ** [comment]
Ok, looks like I also get this error.
I have downloaded the latest version, unzip it and execute the "exe" file.

The problem was in  the logic which checking the latest version from the GitHub:
![image](https://user-images.githubusercontent.com/17333840/41507833-627f6cbc-725c-11e8-87c7-fdc85a7413a6.png)

I never encounter it before, because I used the files which I build myself.

**Comment by xthephreakx** [comment]
well i'm glad you could reproduce the issue !

will be waiting for a fix :D
