### ISSUE TITLE
MangaFox Problem 

### ISSUE THREAD

**Issue by BaganLee** [NguyenDanPhuong/MangaRipper#14]
When i am trying to download some chapter from mangafox its create only the folder and it doesn't have any page downloaded.

**Comment by NguyenDanPhuong** [comment]
Have you tried the latest version (https://github.com/NguyenDanPhuong/MangaRipper/releases/latest). I've fixed mangafox issue yesterday.

**Comment by BaganLee** [comment]
Yes i downloaded it last night and  again it didn't work

**Comment by NguyenDanPhuong** [comment]
MangaFox updates their website again today. Same for MangaShare. I'll fix this once I got home tonight.

**Comment by BaganLee** [comment]
Ok. I would like to ask you if you could add and the mangastream site in the list if possible and keep up the good work

**Comment by NguyenDanPhuong** [comment]
I have fixed MangaFox and MangaHere issues. :) I will take a look at MangaStream when I have time. Atm, I plan to refactor and improve source code a little bit.

**Comment by BaganLee** [comment]
Ok thanks

**Comment by NguyenDanPhuong** [comment]
Sorry not atm, I'm afraid. It's required to re-program using another programming stack/languages which require a lot resource.
