### ISSUE TITLE
Could not load file or assembly 'MangaRipper.Plugin.KissManga

### ISSUE THREAD

**Issue by ArchmageVengard** [NguyenDanPhuong/MangaRipper#140]
Sorry if this issue was already addressed, I'm new to this site and I'm bad at looking for threads
Here's the log file : https://ibb.co/hFJQgo

**Comment by GambitKZ** [comment]
Maybe it's due to old .Net Framework version?

**Comment by ArchmageVengard** [comment]
Tried that, now it won't start at all xD

**Comment by GambitKZ** [comment]
It should be working with ".Net Framework v4.5.2".
Which version do you have?

**Comment by yonixw** [comment]
@GambitKZ little late bu had same problem you need to right-click the dlls in the plugin directory and in the bottom check "Unblock" and click OK. The windows defender blocks downloaded dlls from running... very annoying but hopefully helped you with some viruses ...
