### ISSUE TITLE
MangaRipper.Core error

### ISSUE THREAD

**Issue by eksynn** [NguyenDanPhuong/MangaRipper#144]
"One or more errors occurred."

this happens almost every time it tries to download a chapter, either immediately or after a while, and then it stops completely.
usually at 2%.

Please advise?

error screenshot:
https://cdn.discordapp.com/attachments/505147945050439691/516360963050700804/unknown.png
the log:
[2018-11-25.log](https://github.com/NguyenDanPhuong/MangaRipper/files/2613534/2018-11-25.log)

edit: do we have a discord server yet?

**Comment by NguyenDanPhuong** [comment]
I think we fix this in the latest version
