### ISSUE TITLE
Version 4.6.2 vs 1.0.342?

### ISSUE THREAD

**Issue by eksynn** [NguyenDanPhuong/MangaRipper#147]
how do i download version 4.6.2? the latest version still leads to the version i have now (v1.0.342)
i'm having so many issues with 1.0.342 that i can't even download more than a handful of chapters a day, basically (exaggerated, but you get it)

**Comment by eksynn** [comment]
is this project still even being worked on?
are there any alternative manga downloaders out there?

**Comment by JedBurke** [comment]
@eksynn v4.6.2 is the Microsoft .NET Framework version not the MangaRipper version.
