### ISSUE TITLE
This is a "Dead application"

### ISSUE THREAD

**Issue by ASH1998** [NguyenDanPhuong/MangaRipper#148]
This is a message to @NguyenDanPhuong and users, this app now is a time waste.
Don't bother correcting it or even trying to fix any issues. Fixing one part makes some other part go wrong. The development was not done in a proper way.
Better use some other project or app to download.

**Comment by Anvesh2013** [comment]
did you find any other apps that work?

**Comment by anhxtaiii** [comment]
it was working fine when it worked issa shame

**Comment by NguyenDanPhuong** [comment]
The sites changed. Previously they store images in HTML, now they encrypted and store in JavaScript. To make MangaRipper works again require a big rewrite to execute JavaScript (so we can decrypt and retrieve images URL). It takes time.

Now I have some free time, I will start to rewrite this app from this week.

**Comment by GambitKZ** [comment]
Base on behavior of similar apps - it may be better to return to "PhantomJS".

**Comment by NguyenDanPhuong** [comment]
@GambitKZ 
I've worked on this branch https://github.com/NguyenDanPhuong/MangaRipper/tree/feature/headless-chrome-plugin

Since PhantomJS no longer maintained. I use the Chrome browser in headless mode. Work great so far. MangaFox & MangaHere work again.

**Comment by virtualbjorn** [comment]
How about we use ElectronJS?

**Comment by NguyenDanPhuong** [comment]
@virtualbjorn if we use ElectronJS, we have to write a new application in JavaScript.

I've released a new version to issues with MangaFox & MangaHere.

**Comment by Ever4engel** [comment]
Hello 
this is a dead application ?
You could contribute in this [Hakuneko](https://github.com/manga-download/hakuneko/tree/master) project ^^
