### ISSUE TITLE
error when pressing "Add Prefix Counter"

### ISSUE THREAD

**Issue by misidp** [NguyenDanPhuong/MangaRipper#20]
![error when pressing add prefix counter](https://cloud.githubusercontent.com/assets/24575884/21202488/0e9a0a62-c281-11e6-8fef-ddd32ae63257.jpg)

i'm using windows7 32bit, net framework 4.6 and mangaripper 1.0.135
when pressing "Add Prefix Counter" i got error

Unhandled exception has accoured in your application. If you click
Continue. the application will ignore this error and attempt to continue. If
you click Quit. the application will close immediately

everything is running well(perfect) , except the "Add Prefix Counter" function
please help fix it..

**Comment by misidp** [comment]
version 1.0.102 the "Add Prefix Counter" works perfectly, only trouble downloading from mangafox
![ver1_0_102](https://cloud.githubusercontent.com/assets/24575884/21205239/b5af76b4-c28d-11e6-9706-bbc1d7e8dcdb.jpg)

**Comment by NguyenDanPhuong** [comment]
Thank you for your detailed issue report. I have fixed this problem and add notification when there's new version available.

**Comment by misidp** [comment]
thanks a lot for the improvement Mr. NguyenDanPhuong
please keep mangaripper as simple as possible.
mangaripper is the best! simple and powerfull
