### ISSUE TITLE
Can you add Bato.to?

### ISSUE THREAD

**Issue by RudeBoyEEEE** [NguyenDanPhuong/MangaRipper#22]
What the title says. I really like using Batoto, and would like to use it here. 

http://bato.to/

Thanks!

**Comment by NguyenDanPhuong** [comment]
Sure. I will take a look at this to see if it's possible.

**Comment by NguyenDanPhuong** [comment]
I've added support for this site. You can try the beta version here: https://ci.appveyor.com/project/NguyenDanPhuong/mangaripper/build/1.0.145/artifacts

You may encounter some issues though.

**Comment by RudeBoyEEEE** [comment]
Nice! But is there any way you could make a setting to filter different languages in the site? Also, you may need to add a "Batoto Login" button, I've seen programs like **DomDomSoft Manga Downloader** do this. You should take a look at that one, it could help you improve MangaRipper if you look at how it works.

**Comment by NguyenDanPhuong** [comment]
Currently I use a dummy account to access Batoto, so it can access all titles, chapters. I will make it configurable someday. However I don't want to spend time to implement UI for changing settings. I would create a JSON file to store settings and allow user to edit that file.
