### ISSUE TITLE
Can you auto-alphabetize bookmarks?

### ISSUE THREAD

**Issue by RudeBoyEEEE** [NguyenDanPhuong/MangaRipper#24]
Sorry for another issue post, but I was wondering if you could perhaps auto-alphabetize bookmarks? Maybe make a button to show them besides the toolbar at the top? Just a suggestion, this is a great program!

**Comment by NguyenDanPhuong** [comment]
Ok let me see.

**Comment by Dichter68** [comment]
Hi. How about setting the sort-option of the url-combobox on true.
It would work as simple solution. The only drawback  I see is that it would sort the complete url and not just the name of the manga.

example:
http://mangafox.me/manga/a
http://mangafox.me/manga/e
http://mangafox.me/manga/f
http://www.mangahere.co/manga/b
http://www.mangahere.co/manga/c
http://www.mangahere.co/manga/d

It would help me to find the correct url much faster. :)

**Comment by NguyenDanPhuong** [comment]
I've done. It is on the latest version.
