### ISSUE TITLE
Configurable settings in json file.

### ISSUE THREAD

**Issue by NguyenDanPhuong** [NguyenDanPhuong/MangaRipper#26]
The settings of MangaRipper should store in a json file. User can change settings by editing this file. We will not implement changing settings in UI.

It's similar to some famous text editor (Visual Studio Code, Sublime Text Editor).

**Comment by amayra** [comment]
i think [Notepad++](https://notepad-plus-plus.org/) is better choice

**Comment by GambitKZ** [comment]
>The settings of MangaRipper should store in a json file.
We already have "MangaRipper.exe.config". Why do we need something else?

**Comment by NguyenDanPhuong** [comment]
Recently I added support for Batoto. This site required to login to read manga. I've hard coded a dummy username and password. Let user use their own account is better.

The structure of JSON file show be like this:

{
  "Service.Batoto.Username": "abc",
  "Service.Batoto.Password": "123"
  // Other settings...
}

User can change settings by modifying JSON file. Modify . Config file is harder.

**Comment by GambitKZ** [comment]
I'm returning to my previous proposal:
I can't see the point (except for "this is a trend now") of creating new config file, create "Deserialize" method, e.t.c., when we already have an "app.config" which is handled "out of the box".

**Comment by amayra** [comment]
@GambitKZ  I agree with you

**Comment by NguyenDanPhuong** [comment]
@GambitKZ @amayra 
Xml file is impossible to read and modify by normal user. Xml is a markup language in the root and JSON is much better at presetting data.

Recently, people removing xml config in application and using JSON for that reason.

I'd like this feature implement using Microsoft.Framework.ConfigurationModel package. That way we will have a more loosely couple component.

**Comment by GambitKZ** [comment]
@NguyenDanPhuong 
Ok, I got your point. In this case I propose to use the following structure:
```
{
	"Websites" : {
		"Batoto" : {
			"Username" : "name",
			"Password" : "password"
		},
		"OtherSite" : {
			"Username" : "name",
			"Password" : "password"
		}
	}
}
```
This way it will be opened for extensions.
What do you think?

**Comment by NguyenDanPhuong** [comment]
@GambitKZ 
I think we should create a flat level JSON structure. It's easier to read and maintain. Here's an example from another app.

```
// When enabled, will open files in a new window instead of reusing an existing instance.
  "window.openFilesInNewWindow": true,

  // Controls how folders are being reopened after a restart. Select 'none' to never reopen a folder, 'one' to reopen the last folder you worked on or 'all' to reopen all folders of your last session.
  "window.reopenFolders": "one",

  // Controls if a window should restore to full screen mode if it was exited in full screen mode.
  "window.restoreFullscreen": false,

  // Controls if turning on Zen Mode also puts the workbench into full screen mode.
  "window.fullScreenZenMode": true,

  // Adjust the zoom level of the window. The original size is 0 and each increment above (e.g. 1) or below (e.g. -1) represents zooming 20% larger or smaller. You can also enter decimals to adjust the zoom level with a finer granularity.
  "window.zoomLevel": 0,

  // If enabled, will show the full path of opened files in the window title.
  "window.showFullPath": false,
```

I'd like to inject settings into services and doesn't let plugin access settings directly. They need access to Core project. Let me take a look at how to implement this in the weekend. :)

**Comment by GambitKZ** [comment]
Ok, I will be waiting your implementation

**Comment by NguyenDanPhuong** [comment]
@GambitKZ I've done it. But I will need to refactor it a bit. But it works for now.
