### ISSUE TITLE
site support plugins

### ISSUE THREAD

**Issue by amayra** [NguyenDanPhuong/MangaRipper#27]
and there option i went to discuss with you about site support and i know this well take time 
[from mymanga](https://i.imgsafe.org/e4e939be3c.jpg)
i think is better if you make MangaRipper plugins for site support for easy update without compile an entire  project think this well be more like MangaRipper SDK 
@NguyenDanPhuong what do you think ?

**Comment by NguyenDanPhuong** [comment]
I've already have plan for this. The plugin is a good architect to keep code quality when multiple people working on MangaRipper. Stay tune. :)

**Comment by amayra** [comment]
thanks you and to be honest i try to do it alone in my fork but i end up rewriting MangaRipper from scratch

**Comment by NguyenDanPhuong** [comment]
In the mean time. I will create a wiki page to guide how to add new site. It's pretty simple. Just basic programming knowledge and some regular expression practice.

Basically you will need:

- Create a new class implement IMangaService interface.
- Please look at MangaFoxService, MangaReaderService... to see how it's implemented.
- Register that class in Framework.Init()

**Comment by GambitKZ** [comment]
@amayra @NguyenDanPhuong 
Please, take a look at #29 Pull Request, and tell me what you think.

**Comment by amayra** [comment]
happy new year @GambitKZ i will look into it and get back to you ASAP

**Comment by NguyenDanPhuong** [comment]
Happy new year. :)

I've just comeback from vacation. Let me take a look.

**Comment by NguyenDanPhuong** [comment]
Hi @GambitKZ 

The test for Batoto failed. Can you help to take a look at this. Unfortunately, I have some issues and cannot work on this till the weekend.

Thanks,

**Comment by GambitKZ** [comment]
Sorry, forgot to add Batoto.dll into Unit Test.

**Comment by GambitKZ** [comment]
@amayra 
Should we done something different here, or this implementation is good enough as is, and the issue can be closed?

**Comment by amayra** [comment]
@GambitKZ i think this is perfect thank you so much

**Comment by NguyenDanPhuong** [comment]
We need to make plugin depend on interfaces (of MangaRipper.Core) instead of classes (For ex: NLog classes, SiteInformation class...). However let make it a separate task and close this for now. :)
