### ISSUE TITLE
New icon!

### ISSUE THREAD

**Issue by NguyenDanPhuong** [NguyenDanPhuong/MangaRipper#3]
Need a new icon.

**Comment by amayra** [comment]
I well help you with this one

**Comment by NguyenDanPhuong** [comment]
Thank you. :) I'm very appreciated. I'm looking for a clear, minimal design. Vector graphic. It's should be similar to the current icon but I'm open on any design that look good. Can you share some of your ideals?

**Comment by iYatsumi** [comment]
Hey Dan, i don't know if you were still looking for icon ideas but here's one of mine. I could also change the colors to your preferences or whatever. 

the icon: 
![2](https://cloud.githubusercontent.com/assets/8799430/22178154/5dfd43c8-dffd-11e6-94bb-5688c524f46f.png)

on taskbar:
![a808f76e0d7780f51f8e8f66712c21a2](https://cloud.githubusercontent.com/assets/8799430/22178178/a28c0768-dffd-11e6-9047-3c5fede39db4.png)

File (.ico / 32x32);
https://www.sendspace.com/file/lgq3zo

**Comment by NguyenDanPhuong** [comment]
Thanks. It looks good. Can you change the color a little bit. I'd like it more simple and material/metro (like Android/Windows 10) design like the rest of your icons in the images. Ex: use less color, without reflection... The output format. Can you use icon with multiple resolution or you can upload an png 256x256 then I can convert it.

**Comment by iYatsumi** [comment]
![1](https://cloud.githubusercontent.com/assets/8799430/22187233/825f29c4-e0d0-11e6-8405-d00bd35db833.png)

https://www.sendspace.com/file/tx65wn

- 256x256
- 128x128
- 48x48 
- 32x32 
- 16x16

**Comment by NguyenDanPhuong** [comment]
It's really hard to explain my idea using text. Let me make a quick sketch and comeback later. ;)

**Comment by iYatsumi** [comment]
@NguyenDanPhuong still waiting about that sketch in case you forgot about it

**Comment by NguyenDanPhuong** [comment]
Hi iYatsumi, I'm on vacation for 2 weeks now and only can access internet on my phone. I will create the draft when I get back. Thank you. :)

**Comment by iYatsumi** [comment]
!

**Comment by NguyenDanPhuong** [comment]
@iYatsumi Thank you for reminding but I still cannot come up with the design. I've made a lot of draft but doesn't feel right. I didn't know it was that hard. :(

**Comment by JedBurke** [comment]
@NguyenDanPhuong If you're looking for general UI icons (save, bookmark, etc), [here](https://github.com/Templarian/WindowsIcons) is a repo of flat WP-style icons that you might like.
