### ISSUE TITLE
I can't open wtih winrar and 7-zip the file MangaRipper.exe

### ISSUE THREAD

**Issue by CarmillaVesper** [NguyenDanPhuong/MangaRipper#35]
Whenever I try to open the release 1.0.165 MangaRipper.zip with Winrar and 7zip, I've got a problem extracting the file MangaRipper.exe
It's done the same thing with multiple downloads and comes up with the same error message "cannot open file: file name as archive"

**Comment by JedBurke** [comment]
Please clarify, can you open "MangaRipper.zip" as an archive and extract its files? The file "MangaRipper.exe", as it appears in the image, is a text file and not an archive. Double-click on "MangaRipper" to run the application.

![Screenshot](http://i.imgur.com/3gofGcW.jpg)
