### ISSUE TITLE
Cant start at all.

### ISSUE THREAD

**Issue by CMDRGoro** [NguyenDanPhuong/MangaRipper#36]
Program starts and then closes, no error msg or nothing.

My log:

> 2017-01-19 21:42:39.2682 INFO > Framework.Init() 
2017-01-19 21:42:39.2822 INFO > Worker() 
2017-01-19 21:42:40.4884 INFO Local version: 1.0.140. Remote version: 1.0.165 
2017-01-19 21:43:42.8963 INFO > Framework.Init() 
2017-01-19 21:43:42.9124 INFO > Worker() 
2017-01-19 21:43:53.8885 INFO > Framework.Init() 
2017-01-19 21:43:53.9156 INFO > Worker() 
2017-01-19 21:44:22.7844 INFO > Framework.Init() 
2017-01-19 21:44:22.8104 INFO > Worker() 
2017-01-19 21:44:41.3608 INFO > Framework.Init() 
2017-01-19 21:44:41.3868 INFO > Worker() 
2017-01-19 21:44:45.6462 INFO > Framework.Init() 
2017-01-19 21:44:45.6632 INFO > Worker() 
2017-01-19 21:44:58.6086 INFO > Framework.Init() 
2017-01-19 21:44:58.6367 INFO > Worker() 
2017-01-19 21:46:05.8014 INFO > Framework.Init() 
2017-01-19 21:46:05.9387 INFO > Worker() 
2017-01-19 21:46:15.8621 INFO > Framework.Init() 
2017-01-19 21:46:15.8792 INFO > Worker() 
2017-01-19 21:47:02.0189 INFO > Framework.Init() 
2017-01-19 21:47:02.0360 INFO > Worker() 
2017-01-19 21:50:09.0013 INFO > Framework.Init() 
2017-01-19 21:50:09.0174 INFO > Worker() 

I assume its netframework related issue?
Does it requires spme special version?
(previous relese worked fine)

**Comment by NguyenDanPhuong** [comment]
It seems you missed the Plugins folder. Please check if you have enough files and folders as listed below.

![image](https://cloud.githubusercontent.com/assets/20277465/22134444/91f515a2-def9-11e6-9e99-522a212ee4e0.png)

**Comment by CMDRGoro** [comment]
it looks to me like i have it all:

[http://i.imgur.com/NIeO6Ws.jpg](url)
[http://i.imgur.com/iedShjs.jpg](url)

**Comment by NguyenDanPhuong** [comment]
Can you try with the latest beta version: 

https://ci.appveyor.com/project/NguyenDanPhuong/mangaripper/branch/dev/artifacts

I've added more exception logging so the log is more detailed.

**Comment by CMDRGoro** [comment]
Im at work atm.
Will check as soon as ill galet back.

20 sty 2017 05:27 "NguyenDanPhuong" <notifications@github.com> napisał(a):

**Comment by CMDRGoro** [comment]
My current log from that beta:

> 2017-01-20 16:02:00.3641 | INFO | Program | > Main() 
2017-01-20 16:02:00.3882 | INFO | FrameworkProvider | > Framework.Init() 
2017-01-20 16:02:00.3882 | INFO | WorkerController | > Worker() 
2017-01-20 16:02:00.4102 | FATAL | Program | Unhandled Exception 
System.IO.FileLoadException: Nie można załadować pliku lub zestawu 'file:///E:\MangaRipper\Plugins\MangaRipper.Plugin.Batoto.dll' lub jednej z jego zależności. Operacja nie jest obsługiwana. (Wyjątek od HRESULT: 0x80131515)
Nazwa pliku: 'file:///E:\MangaRipper\Plugins\MangaRipper.Plugin.Batoto.dll' ---> System.NotSupportedException: Podjęto próbę załadowania zestawu z lokalizacji sieciowej. W starszych wersjach programu .NET Framework próba ta spowodowałaby uruchomienie zestawu w trybie piaskownicy. W tej wersji programu .NET Framework zasady CAS domyślnie nie są włączone, więc to załadowanie może być niebezpieczne. Jeśli ma ono na celu uruchomienie zestawu w trybie piaskownicy, włącz przełącznik loadFromRemoteSources. Aby uzyskać więcej informacji, zobacz http://go.microsoft.com/fwlink/?LinkId=155569.
   w System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   w System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   w System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   w System.Reflection.Assembly.LoadFrom(String assemblyFile)
   w MangaRipper.Core.Services.PluginService.LoadPluginAssemblies(String path) w C:\projects\mangaripper\MangaRipper.Core\Services\PluginService.cs:wiersz 51
   w MangaRipper.Core.Services.PluginService.LoadWebPlugins() w C:\projects\mangaripper\MangaRipper.Core\Services\PluginService.cs:wiersz 32
   w MangaRipper.Core.Providers.FrameworkProvider.Init(String pluginPath, String configFile) w C:\projects\mangaripper\MangaRipper.Core\Providers\FrameworkProvider.cs:wiersz 34
   w MangaRipper.Program.Main() w C:\projects\mangaripper\MangaRipper\Program.cs:wiersz 24


It seems to be some net framework issue...

**Comment by NguyenDanPhuong** [comment]
It's a security feature prevent loading plugins from a remote location. Are you running MangaRipper over a shared folder?

**Comment by CMDRGoro** [comment]
No, E is my local drive.
Runing from admin account changes nothing,

**Comment by NguyenDanPhuong** [comment]
Windows detects file are copied from network and block them. Can you right click files and choose Properties then unblock them. For every exe and dll files.

Can you tell me extract ly what are you doing after download app. What unzip application you're using.

**Comment by CMDRGoro** [comment]
I did that properities -> unblock for all files (had to do it one by one, cant do it in bulk) and now it runs :D .

![image](https://cloud.githubusercontent.com/assets/25233098/22156172/6c26709e-df32-11e6-8973-96fbc9c6e2c8.png)

Why did this happen? I had no problems with previous versions...

**Comment by CMDRGoro** [comment]
Aaaaaaand not good yet.

![image](https://cloud.githubusercontent.com/assets/25233098/22156268/d72e81a6-df32-11e6-99a8-ccda7d24e55f.png)

I get error when trying to DL...

**Comment by NguyenDanPhuong** [comment]
It's because Windows detect those files are copied from internet and block them. It's strange because you download zip file only and create all files from zip file so it doesn't count as downloaded from internet. May be due to the unzip application you're using.

**Comment by CMDRGoro** [comment]
I tried diferent sites and its only when downloading from mangafox, tried batato and mangahere and they work fine.

ps im using winrar as always.

**Comment by NguyenDanPhuong** [comment]
Can you re-upload the log file for the new can't find path issue?

**Comment by CMDRGoro** [comment]
> 2017-01-21 13:18:06.2834 | INFO | Program | > Main() 
2017-01-21 13:18:06.3035 | INFO | FrameworkProvider | > Framework.Init() 
2017-01-21 13:18:06.3035 | INFO | WorkerController | > Worker() 
2017-01-21 13:18:06.7356 | INFO | Batoto | Current Username: gufrohepra. New Username: gufrohepra 
2017-01-21 13:18:06.7356 | INFO | Batoto | Current Password: 123. New Password: 123 
2017-01-21 13:19:25.1663 | INFO | WorkerController | > FindChapters: http://mangafox.me/manga/kidou_senshi_gundam_seed_frame_astrays/ 
2017-01-21 13:19:25.1844 | INFO | MangaFox | > FindChapters(): http://mangafox.me/manga/kidou_senshi_gundam_seed_frame_astrays/ 
2017-01-21 13:19:25.1844 | INFO | DownloadService | > DownloadStringAsync(String): http://mangafox.me/manga/kidou_senshi_gundam_seed_frame_astrays/ 
2017-01-21 13:19:25.5734 | INFO | ParserHelper | > ParseGroup: <a href="(?<Value>[^"]+)" title="(|[^"]+)" class="tips">(?<Name>[^<]+)</a> 
2017-01-21 13:19:44.5800 | INFO | WorkerController | > DownloadChapter: http://mangafox.me/manga/kidou_senshi_gundam_seed_frame_astrays/v01/c001/1.html To: C:\Users\Grzyb\Desktop\My Mangas\test 
2017-01-21 13:19:44.5880 | INFO | DownloadService | > DownloadStringAsync(String): http://mangafox.me/manga/kidou_senshi_gundam_seed_frame_astrays/v01/c001/1.html 
2017-01-21 13:19:44.8487 | INFO | ParserHelper | > Parse: <option value="(?<Value>[^"]+)" (|selected="selected")>\d+</option> 
2017-01-21 13:19:44.8627 | INFO | DownloadService | > DownloadStringAsync(IEnumerable) - Total: 76 
2017-01-21 13:19:44.8627 | INFO | DownloadService | > DownloadStringAsync(String): http://mangafox.me/manga/kidou_senshi_gundam_seed_frame_astrays/v01/c001/1.html 
2017-01-21 13:19:45.1094 | INFO | DownloadService | > DownloadStringAsync(String): http://mangafox.me/manga/kidou_senshi_gundam_seed_frame_astrays/v01/c001/2.html 
2017-01-21 13:19:45.2307 | ERROR | WorkerController | Failed to download chapter: http://mangafox.me/manga/kidou_senshi_gundam_seed_frame_astrays/v01/c001/1.html 
System.Net.WebException: Serwer zdalny zwrócił błąd: (503) Serwer jest niedostępny.
   w System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   w System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Services.DownloadService.<DownloadStringAsync>d__10.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Services\DownloadService.cs:wiersz 49
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Services.DownloadService.<DownloadStringAsync>d__11.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Services\DownloadService.cs:wiersz 76
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Plugin.MangaFox.MangaFox.<FindImanges>d__5.MoveNext() w C:\projects\mangaripper\MangaRipper.Plugin.MangaFox\MangaFox.cs:wiersz 60
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<DownloadChapterInternal>d__7.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 111
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<>c__DisplayClass5_0.<<Run>b__0>d.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 57
2017-01-21 13:19:45.2868 | ERROR | FormMain | System.Net.WebException: Serwer zdalny zwrócił błąd: (503) Serwer jest niedostępny.
   w System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   w System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Services.DownloadService.<DownloadStringAsync>d__10.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Services\DownloadService.cs:wiersz 49
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Services.DownloadService.<DownloadStringAsync>d__11.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Services\DownloadService.cs:wiersz 76
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Plugin.MangaFox.MangaFox.<FindImanges>d__5.MoveNext() w C:\projects\mangaripper\MangaRipper.Plugin.MangaFox\MangaFox.cs:wiersz 60
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<DownloadChapterInternal>d__7.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 111
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<>c__DisplayClass5_0.<<Run>b__0>d.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 62
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<Run>d__5.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 50
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.FormMain.<StartDownload>d__10.MoveNext() w C:\projects\mangaripper\MangaRipper\Form\FormMain.cs:wiersz 123
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.FormMain.<btnDownload_Click>d__9.MoveNext() w C:\projects\mangaripper\MangaRipper\Form\FormMain.cs:wiersz 102 
System.Net.WebException: Serwer zdalny zwrócił błąd: (503) Serwer jest niedostępny.
   w System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   w System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Services.DownloadService.<DownloadStringAsync>d__10.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Services\DownloadService.cs:wiersz 49
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Services.DownloadService.<DownloadStringAsync>d__11.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Services\DownloadService.cs:wiersz 76
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Plugin.MangaFox.MangaFox.<FindImanges>d__5.MoveNext() w C:\projects\mangaripper\MangaRipper.Plugin.MangaFox\MangaFox.cs:wiersz 60
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<DownloadChapterInternal>d__7.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 111
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<>c__DisplayClass5_0.<<Run>b__0>d.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 62
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<Run>d__5.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 50
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.FormMain.<StartDownload>d__10.MoveNext() w C:\projects\mangaripper\MangaRipper\Form\FormMain.cs:wiersz 123
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.FormMain.<btnDownload_Click>d__9.MoveNext() w C:\projects\mangaripper\MangaRipper\Form\FormMain.cs:wiersz 102
2017-01-21 13:20:03.1444 | INFO | WorkerController | > DownloadChapter: http://mangafox.me/manga/kidou_senshi_gundam_seed_frame_astrays/v01/c001/1.html To: C:\Users\Grzyb\Desktop\My Mangas\test 
2017-01-21 13:20:03.1444 | INFO | DownloadService | > DownloadStringAsync(String): http://mangafox.me/manga/kidou_senshi_gundam_seed_frame_astrays/v01/c001/1.html 
2017-01-21 13:20:03.3910 | INFO | ParserHelper | > Parse: <option value="(?<Value>[^"]+)" (|selected="selected")>\d+</option> 
2017-01-21 13:20:03.3910 | INFO | DownloadService | > DownloadStringAsync(IEnumerable) - Total: 76 
2017-01-21 13:20:03.3910 | INFO | DownloadService | > DownloadStringAsync(String): http://mangafox.me/manga/kidou_senshi_gundam_seed_frame_astrays/v01/c001/1.html 
2017-01-21 13:20:03.4993 | ERROR | WorkerController | Failed to download chapter: http://mangafox.me/manga/kidou_senshi_gundam_seed_frame_astrays/v01/c001/1.html 
System.Net.WebException: Serwer zdalny zwrócił błąd: (503) Serwer jest niedostępny.
   w System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   w System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Services.DownloadService.<DownloadStringAsync>d__10.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Services\DownloadService.cs:wiersz 49
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Services.DownloadService.<DownloadStringAsync>d__11.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Services\DownloadService.cs:wiersz 76
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Plugin.MangaFox.MangaFox.<FindImanges>d__5.MoveNext() w C:\projects\mangaripper\MangaRipper.Plugin.MangaFox\MangaFox.cs:wiersz 60
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<DownloadChapterInternal>d__7.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 111
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<>c__DisplayClass5_0.<<Run>b__0>d.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 57
2017-01-21 13:20:03.4993 | INFO | PackageCbzHelper | Creating Zip from `C:\Users\Grzyb\Desktop\My Mangas\test\Kidou Senshi Gundam Seed Frame Astrays 1` to `C:\Users\Grzyb\Desktop\My Mangas\test\Kidou Senshi Gundam Seed Frame Astrays 1.cbz` 
2017-01-21 13:20:03.5163 | ERROR | FormMain | System.IO.DirectoryNotFoundException: Nie można odnaleźć części ścieżki „C:\Users\Grzyb\Desktop\My Mangas\test\Kidou Senshi Gundam Seed Frame Astrays 1”.
   w System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   w System.IO.FileSystemEnumerableIterator`1.CommonInit()
   w System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   w System.IO.DirectoryInfo.EnumerateFileSystemInfos(String searchPattern, SearchOption searchOption)
   w System.IO.Compression.ZipFile.DoCreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, Encoding entryNameEncoding)
   w MangaRipper.Core.Helpers.PackageCbzHelper.Create(String startPath, String zipPath) w C:\projects\mangaripper\MangaRipper.Core\Helpers\PackageCbzHelper.cs:wiersz 18
   w MangaRipper.Core.Controllers.WorkerController.<>c__DisplayClass5_0.<<Run>b__0>d.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 71
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<Run>d__5.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 50
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.FormMain.<StartDownload>d__10.MoveNext() w C:\projects\mangaripper\MangaRipper\Form\FormMain.cs:wiersz 123
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.FormMain.<btnDownload_Click>d__9.MoveNext() w C:\projects\mangaripper\MangaRipper\Form\FormMain.cs:wiersz 102 
System.IO.DirectoryNotFoundException: Nie można odnaleźć części ścieżki „C:\Users\Grzyb\Desktop\My Mangas\test\Kidou Senshi Gundam Seed Frame Astrays 1”.
   w System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   w System.IO.FileSystemEnumerableIterator`1.CommonInit()
   w System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   w System.IO.DirectoryInfo.EnumerateFileSystemInfos(String searchPattern, SearchOption searchOption)
   w System.IO.Compression.ZipFile.DoCreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, Encoding entryNameEncoding)
   w MangaRipper.Core.Helpers.PackageCbzHelper.Create(String startPath, String zipPath) w C:\projects\mangaripper\MangaRipper.Core\Helpers\PackageCbzHelper.cs:wiersz 18
   w MangaRipper.Core.Controllers.WorkerController.<>c__DisplayClass5_0.<<Run>b__0>d.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 71
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<Run>d__5.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 50
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.FormMain.<StartDownload>d__10.MoveNext() w C:\projects\mangaripper\MangaRipper\Form\FormMain.cs:wiersz 123
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.FormMain.<btnDownload_Click>d__9.MoveNext() w C:\projects\mangaripper\MangaRipper\Form\FormMain.cs:wiersz 102
2017-01-21 13:20:08.1457 | INFO | Program | < Main() 


It seems to be same problem that guy is having:
[https://github.com/NguyenDanPhuong/MangaRipper/issues/39](url)

**Comment by NguyenDanPhuong** [comment]
Ok. I think I've found the problem. :) MangaFox returns error when you made too many connections to their server in a short time. You may have run 2 instance of MangaRipper to download from MangaFox or download and browsing MangaFox at the same time.

**Comment by CMDRGoro** [comment]
I tried running to copies and DLing at same time got same error.
Same for DL while browsing :(

**Comment by NguyenDanPhuong** [comment]
I've made this into F.A.Q. Let close this for now.
