### ISSUE TITLE
Unable to uncheck the "Save as Folder" Box 

### ISSUE THREAD

**Issue by iYatsumi** [NguyenDanPhuong/MangaRipper#42]
Minor issue but users should be able to uncheck the "**save as folder**" option when choosing the .cbz format since it isn't needed or at least have the option to choose whether or not they want that option so that they don't end up downloading the .cbz format with the folder format.

![a04083aaad5a67a9ea022031f8e2539c](https://cloud.githubusercontent.com/assets/8799430/22187532/49b95148-e0d6-11e6-9d0b-7ad34d2a2d12.png)

**Comment by NguyenDanPhuong** [comment]
This is in my plans. But I'd like to implement a more stable + controllable bookmark first. Then I will create a plugin system to allow export to multiple formats.

**Comment by NguyenDanPhuong** [comment]
Fixed in latest version
