### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by iYatsumi** [NguyenDanPhuong/MangaRipper#43]
i was wondering if there was a way to customize the UI of the app with the source code you provided or something along the files that came with the app. Im still new to programming so i don't really know how everything works.  i do have ms visual 2013 if that's relevant somehow.

**Comment by NguyenDanPhuong** [comment]
For better UI. I'd like to move from WinForm to WPF. Here is a tutorial about WPF if you want to take a look.

**Comment by iYatsumi** [comment]
where's the tutorial ? and i'll look into it for sure, thanks !

**Comment by NguyenDanPhuong** [comment]
Sorry I forgot to post link :) http://www.wpf-tutorial.com/
