### ISSUE TITLE
Mangaripper will not start

### ISSUE THREAD

**Issue by JohnJTR** [NguyenDanPhuong/MangaRipper#44]
I'm using the latest version 1.0.173 but when I extract it and launch the program, nothing happens. Windows smartscreen warns me about it on the first try but I run it anyway. I tried disabling it to see if it was preventing it from launching regardless, but it still refuses to start.

CMDRGoro seems to have had this issue, but I don't seem to understand how the issue was resolved.

**Comment by NguyenDanPhuong** [comment]
I update the F.A.Q to cover this case and include a short how to fix. Please see [F.A.Q.](https://github.com/NguyenDanPhuong/MangaRipper/wiki/F.A.Q.)
