### ISSUE TITLE
Save To Path Problem 

### ISSUE THREAD

**Issue by BaganLee** [NguyenDanPhuong/MangaRipper#48]
Hey. I don't know why i am always here to tell you about some error/problem i have find but w/e. 
When i am trying to change the path to another location from the prefix you have as a default it give me this error  http://imgur.com/a/psd4B and the logs http://pastebin.com/MtKNqy3g if you need it.

**Comment by NguyenDanPhuong** [comment]
I've checked and the problem is you cannot download to another disk volume. I'll push a fix soon.

**Comment by BaganLee** [comment]
Ok thanks

**Comment by NguyenDanPhuong** [comment]
I've fixed this. Sorry for the long waiting.
