### ISSUE TITLE
Unable to run since 1.0.104

### ISSUE THREAD

**Issue by Demorra** [NguyenDanPhuong/MangaRipper#55]
I have tried all the releases from 1.0.140 up to 1.0.208, but I am only able to run the 1.0.140 release.
Running on Windows 10 Home (Build 14393).
I have tried running as administrator.
I have tried running in compatibility modes for Vista, Vista SP1, Vista SP2,7, 8, and natively on 10.

**Comment by JedBurke** [comment]
If it exists, please upload the text file with the latest date in the *%AppData%\MangaRipper\Logs* folder.

In the meanwhile, please try what was suggested in #50. The [Wiki](https://github.com/NguyenDanPhuong/MangaRipper/wiki/F.A.Q.#cannot-start-mangaripper-the-log-file-shows-nothing) has more.

**Comment by Demorra** [comment]
I tried the powershell fix [Dir "<path>" -Recurse | Unblock-File] to no avail. And there's no logs of when I try to use the newer version. Just logs of 1.0.104.

**Comment by JedBurke** [comment]
@Demorra No worries, glad you got your problem solved.
