### ISSUE TITLE
Not Showing All Chapters from some Mangas

### ISSUE THREAD

**Issue by Sher1234** [NguyenDanPhuong/MangaRipper#56]
Using The MangaRipper 1.0.208 its the best & easy to use tool but 
The Manga: Detective Conan
Site: http://kissmanga.com/Manga/Detective-Conan
Contains Over: 989 Chapters 
But it just Showing Chapters after 353
I tried to refresh (get chapters) many times but still no luck

Thanks for amazing tool

**Comment by BaganLee** [comment]
Have you try to downloaded from another site e.g mangahere.com and if you have tried and  does it give you the same chapters as kissmanga . If it makes the same problem  post the log (you can find them at location > log and copy/past the newest here). Just something you need to know i am not going to help you fix your problem, if you do what i am saying you to do is going to be easier for some people to pick the problem and help you.

**Comment by NguyenDanPhuong** [comment]
This is indeed is a bug. I will fix it in the next release. Thanks for reporting.

**Comment by Sher1234** [comment]
No Problem in that
& Thanks for amazing tool

**Comment by NguyenDanPhuong** [comment]
@JedBurke Can you help to create a pull request if you manage to fix this one? Thanks.

**Comment by JedBurke** [comment]
@NguyenDanPhuong Okay, let me see what I can do about it.

**Comment by Sher1234** [comment]
It Worked all Chapters are now showing
Thanks
