### ISSUE TITLE
Unable to run .exe

### ISSUE THREAD

**Issue by kristycyw** [NguyenDanPhuong/MangaRipper#65]
Hi, Im not sure what the issue is, but I have downloaded the zip and unpacked it but am unable to run the .exe file. Not sure what the issue might be, thank you for your time. I'm on windows 10

**Comment by GambitKZ** [comment]
Sorry, but it's too vague.
Did you get any errors during executions?
Does your firewall/antivirus gave any errors?
Can you see a log file?

**Comment by kristycyw** [comment]
That's the thing, I'm not sure if its a permissions issue but when i click on the .exe file nothing happens at all. The cursor turns into a blue circle (running) and then nothing happens at all. I tried giving admin privileges,  a window pops up asking for approval, I agree and then again, nothing happens no matter how long I wait. could something be blocking the program?

**Comment by kristycyw** [comment]
Ah, I found the problem, you have to extract the file with 7zip instead of the windows unzip function.
