### ISSUE TITLE
mscorlib: the process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by AntiSora** [NguyenDanPhuong/MangaRipper#69]
not exactly sure what this means but it appears to be interrupting my downloads at about halfway trough (52%,53%)
![image](https://cloud.githubusercontent.com/assets/26870998/24832046/bf997d60-1c7d-11e7-8657-d3094e3e1789.png)

**Comment by NguyenDanPhuong** [comment]
It possible that your computer is infected by the virus. It try access files on your computer and make MangaRipper cannot manipulate files. Do you have any AV installed?

**Comment by AntiSora** [comment]
I have an avast, ill try to mess with it
