### ISSUE TITLE
Option to download Comics

### ISSUE THREAD

**Issue by Huenyan** [NguyenDanPhuong/MangaRipper#70]
Hi, huge fan of your work here. This software helped me to save a lot of bandwidth in my phone. 
Just want to ask if there is any plan to include an option to download from comics sites, like readcomics.tv.

**Comment by JedBurke** [comment]
Not the developer, so I can't say whether or not there will be support for it. However, in the meantime, [here's](https://github.com/NguyenDanPhuong/MangaRipper/files/908282/MangaRipper.Plugin.ReadComics.dll.zip) a (poorly tested) plugin which provides support for "ReadComics.tv". 

To use it, extract the zip file into *MangaRipper\Plugins* and run MangaRipper.

In the event it doesn't work, make sure *MangaRipper.Plugin.ReadComics.dll* isn't blocked. You can do this by right-clicking the file and clicking *Properties*.

**Comment by Huenyan** [comment]
@JedBurke 
It did not work. I got the message "Cannot find service to download". And when I click on the link in the grid with the sites I got [this one](http://i.imgur.com/UtOeadF.jpg).

I notice that all the other plugins have a .pdb file and your doesn't, maybe that is the problem.

**Comment by JedBurke** [comment]
@Huenyan The PDB file shouldn't have had anything to do with it as I checked if it worked before excluding it. It was a bug caused in a place where I never tested... Anyway, [here's](https://github.com/NguyenDanPhuong/MangaRipper/files/913048/Plugins.zip) the updated DLL including its PDB for peace of mind. :) 

Usage is the same as before, you may have to click 'Unblock' to get it to work.

**Comment by Huenyan** [comment]
It worked, thanks.

**Comment by JedBurke** [comment]
I'm glad to hear it, enjoy.

**Comment by juely01** [comment]
Can somebody teach me where to put the plugin? I can't find it. Noobie here.

Thank you.

**Comment by JedBurke** [comment]
@juely01 Once you extract the downloaded MangaRipper zip file, you'll see a folder called **Plugins** in the extracted folder. Copy the extracted plugin, MangaRipper.Plugin.ReadComics.dll, to that folder and restart MangaRipper.

However, the [latest](https://github.com/NguyenDanPhuong/MangaRipper/releases/tag/1.0.264) version of MangaRipper comes bundled with the ReadComics.tv plugin.

**Comment by Huenyan** [comment]
The puglin used to work, but now the site is dead. I'm using http://readcomiconline.to now.

**Comment by JedBurke** [comment]
@Huenyan I'm a bit hazy since I haven't visited the site after building the plugin. Would you mind confirming if http://readcomics.website is the same site as readcomics.tv just with a different domain?

**Comment by Huenyan** [comment]
@JedBurke I don't think it's the same.

**Comment by JedBurke** [comment]
@Huenyan That's unfortunate, thanks for checking.
