### ISSUE TITLE
Not Running

### ISSUE THREAD

**Issue by redxyellow** [NguyenDanPhuong/MangaRipper#72]
It does not run on my laptop. I'm on windows 10 and I have tried running it without antivirus still no luck. :/

**Comment by NguyenDanPhuong** [comment]
Hi @redxyellow, Can you check if the download zip file is blocked or not as mention in F.A.Q. section. https://github.com/NguyenDanPhuong/MangaRipper/wiki/F.A.Q.

**Comment by alfreeland** [comment]
Same issue

**Comment by pszegryf** [comment]
Same issue but have windows 7.
