### ISSUE TITLE
Re download problem and slow downloads

### ISSUE THREAD

**Issue by lightyagami97** [NguyenDanPhuong/MangaRipper#75]
just before completing the file download at around 90%, the download stops and the start download button activates for clicking and when you click that the download resumes from 0. Also my internet speed remains in mbs but it take like 5 min to download 10 mb. Please give a nice update asap or suggest a solution soon.

**Comment by GambitKZ** [comment]
> just before completing the file download at around 90%, the download stops

And you didn't get any errors? What about logs, did you get anything there?

**Comment by lightyagami97** [comment]
Well, it says that unable to copy to stream. Also please suggest anything that i can do to support multiple downloads at once.

**Comment by lightyagami97** [comment]
And also the solution as to how to assign more bandwidth to this software or how can it be made to download faster.

**Comment by retrogade** [comment]
I'm facing the same problem. Downloads stop midway with an error stating "Download cancelled! Reason: Error while copying content to a stream" . I've tried the same manga from different sites, keep getting this error. And I also second on the speed, seems quite slow.  The times it has worked, it's been great. Thanks

**Comment by NguyenDanPhuong** [comment]
It the network related stuff, I cannot do anything about this.
