### ISSUE TITLE
MangaFox

### ISSUE THREAD

**Issue by iYatsumi** [NguyenDanPhuong/MangaRipper#8]
it's not letting download from Mangafox.me , download basically stops at 50% and gives me the error 403 forbidden, i would use the other sites but the manga i wanted isn't listed there

**Comment by NguyenDanPhuong** [comment]
Thank for reporting. Can you let me know the manga that cause issue?

**Comment by iYatsumi** [comment]
it was the Days Manga 
Publisher: Kodansha

but i have also noticed that any other manga that i try from Mangafox isn't working while the other sites works fine in comparison.

**Comment by NguyenDanPhuong** [comment]
This issue is fixed!

**Comment by iYatsumi** [comment]
Hi, 
thank you for responding so quickly but could you please give me instructions on what i should do with that code because im still pretty new to programming, i have Unreal X-Editor in hands.

**Comment by NguyenDanPhuong** [comment]
You just need to download latest release and run. https://github.com/NguyenDanPhuong/MangaRipper/releases

**Comment by iYatsumi** [comment]
thank for providing the assistance in such short notice, i'm happy to confirm that the resolution worked.
