### ISSUE TITLE
Parse content Failed ! 

### ISSUE THREAD

**Issue by iYatsumi** [NguyenDanPhuong/MangaRipper#81]
![image](https://user-images.githubusercontent.com/8799430/27887799-985ece8a-61b0-11e7-8772-ae2c6de799be.png)

Worked fine before, tried other sites but no luck, but was stable when downloading from bato. 

**the blanks are the title of my folders, this has never been an issue since it worked before 

[2017-07-05.txt](https://github.com/NguyenDanPhuong/MangaRipper/files/1126222/2017-07-05.txt)

**Comment by iYatsumi** [comment]
**Update**

Tried again with Mangareader and it worked fine so probly the server link of bako is corrupted or something

**Comment by NguyenDanPhuong** [comment]
I've update a fix for Batoto. Can you check again

**Comment by RudeBoyEEEE** [comment]
Redownloaded the software, still had the same problem until I used my own Batoto account. Seems to work fine now!
