### ISSUE TITLE
False virus positive

### ISSUE THREAD

**Issue by vomov** [NguyenDanPhuong/MangaRipper#89]
According to F-secure, the exe contains Application:W32/Generic.de47c27dd4!Online

**Comment by GambitKZ** [comment]
Have you tried other Antiviruses? For example - https://virusdesk.kaspersky.com/
![image](https://user-images.githubusercontent.com/17333840/33675658-7fead9ce-dadd-11e7-868d-a14db42cd0cf.png)

But asking this kind of questions in the project with open code - quite a joke.
I believe we can close this issue.

**Comment by vomov** [comment]
Nobody asked a question; I just noticed F-secure was being annoying (as usual), and thought I'd note it down, so non-technical individuals would be able to find it under the heading 'false positive' and calm down.
