### ISSUE TITLE
Mangafox Error

### ISSUE THREAD

**Issue by BaganLee** [NguyenDanPhuong/MangaRipper#91]
As the title say when I am trying to download a chapter from the site it gives me this error : https://imgur.com/a/eQowq

**Comment by JedBurke** [comment]
Jurassic is in use by the KissManga plugin, are you sure you aren't referring to that? Regardless, please upload your log so we can see what's wrong.

**Comment by BaganLee** [comment]
Can you reminded me where I can find the log files ?

**Comment by JedBurke** [comment]
Newer versions have a menu item "Locations" on the top left corner. Click that then "Logs". Once Explorer opens, you would be looking for the text file with the date of when the error occurred. (i.e. 2017-09-05.txt)

**Comment by BaganLee** [comment]
https://pastebin.com/KPvw1Knx This is the logs you ask for.

**Comment by JedBurke** [comment]
I need the latest one where you tried to download chapters and it failed. Never mind that for now as there was a change in the website which broke the plugin.

I've attached a [temporary fix](https://github.com/NguyenDanPhuong/MangaRipper/files/1283077/KM_Update.zip) for the plugin. Right-click the zip file for 'Properties' and click 'Unblock' if necessary. Finally extract the files into the MangaRipper/Plugins folder.

----
Referencing #92 as they appear to have the same KissManga bug in common.

**Comment by BaganLee** [comment]
https://pastebin.com/gpxNET9z It still give my the same error.

**Comment by JedBurke** [comment]
Was able to download the same chapter of Gangsta with the update. Used the latest version of MangaRipper (v1.0.264) as the base. If it still persists, check if *Plugins/Jurassic.dll* is unblocked as well.

**Comment by BaganLee** [comment]
The update you made work for my too. Thanks for the patch

**Comment by JedBurke** [comment]
No problem, I'm glad you can download again.
