### ISSUE TITLE
Download cancelled! Reason: Could not find a part of the path

### ISSUE THREAD

**Issue by martianph** [NguyenDanPhuong/MangaRipper#94]
This happens when you select the"Save in Series folder" or even when you type in a wanted folder destination in the "Save Destination" area. 
Thing is, the program doesn't create the folders, so it just stops 'cause it doesn't know what to do. I tried creating the folders myself and the errors stopped. I guess what needs to be done it to let the program create new folders by automatically? 

Also thank you, this program helps a lot. And I don't even mind if you don't do what I suggested, we just have to do it ourselves. It works great as it stands, and I've been using it for ages. :) 
[2017-09-26.log](https://github.com/NguyenDanPhuong/MangaRipper/files/1333508/2017-09-26.log)

**Comment by JedBurke** [comment]
I'm not the main developer, but the one who implemented the "Save in Series folder" feature. Admittedly, I never contemplated the creation of the CBZ file or more specifically, the existence of its directory, when implementing the option. Quitting on a non-existent directory is indeed the case.
